#
# ~/.bashrc

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ll='ls -l --color=auto'
alias ls='ls -l --color=auto'
alias grep='grep --color=auto'
alias vi='nvim'
PS1='\[\e[96m\]\w\n\[\e[0;1m\]>\[\e[0m\] '


